### ISSUE TITLE
relevance in 2021 and how to use this plugin with vscode

### ISSUE THREAD

**Issue by sohrabsaran** [chriseaton/jsdoc-plugin-intersection#3]
I have the following questions:
Q1. Is this plugin still relevant in 2021, or there some other solution recommended?
Q2. How exactly does one use this plugin with Vs Code? Specifically, where is the JSDOC configuration file located? If the configuration file needs to be created, what name should it have, can a template be provided, and how does this configuration file get read by VsCode - is there some other configuration needed to point to this JSDoc config file?

**Comment by scottapow** [comment]
I have this same question. Most examples for setting up a jsdoc config file do so for the CLI. But for usage with intellisense via VS Code, it is not clear if there is any conventions in use.

**Comment by chriseaton** [comment]
1) Yes. per the readme, see [here](https://github.com/jsdoc/jsdoc/issues/1285).
2) If you want to learn more about jsdoc, you can start [here](https://jsdoc.app/). There are numerous ways to utilize jsdoc in javascript projects.
